=== crlizcan/CloudWeb/Lenguajes de marcas/ResOdi.dtd
<!ELEMENT ResOdi (Administradores,Usuarios,Incidencias,Platos,Alergenos,Promociones,Pedidos,Reservas,Tipos_Platos,Pedidos_Platos,Alergenos_Platos,Pedidos_Promociones)>
<!ELEMENT Administradores (Cuenta+)>
<!ELEMENT Cuenta (Usuario,Password,NIF?,Nombre,Apellidos,Telefono,Direccion)>
<!ELEMENT Usuario (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellidos (#PCDATA)>
<!ELEMENT Telefono (#PCDATA)>
<!ELEMENT Direccion (#PCDATA)>
<!ELEMENT Usuarios (Cuenta+)>
<!ELEMENT Incidencias (Incidencia+)>
<!ELEMENT Incidencia (Codigo,Descripcion,Fecha_Inicio,Fecha_Solucion?,Usuario_Admin,Usuario_Usu)>
<!ELEMENT Codigo (#PCDATA)>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Fecha_Inicio (#PCDATA)>
<!ELEMENT Fecha_Solucion (#PCDATA)>
<!ELEMENT Usuario_Admin (#PCDATA)>
<!ELEMENT Usuario_Usu (#PCDATA)>
<!ELEMENT Platos (Plato+)>
<!ELEMENT Plato (Codigo,Nombre,Codigo_tipo,Precio)>
<!ELEMENT Codigo_tipo (#PCDATA)>
<!ELEMENT Precio (#PCDATA)>
<!ELEMENT Alergenos (Alergeno+)>
<!ELEMENT Alergeno (Codigo,Nombre,Imagen)>
<!ELEMENT Imagen (#PCDATA)>
<!ELEMENT Promociones (Promocion+)>
<!ELEMENT Promocion (Codigo,Porcentaje,Descripcion)>
<!ELEMENT Porcentaje (#PCDATA)>
<!ELEMENT Pedidos (Pedido+)>
<!ELEMENT Pedido (Codigo,Precio_Total,Usuario_Usu,Direccion,Mensaje?)>
<!ELEMENT Precio_Total (#PCDATA)>
<!ELEMENT Mensaje (#PCDATA)>
<!ELEMENT Reservas (Reserva+)>
<!ELEMENT Reserva (Usuario_Usu,Fecha_hora,Mesa,Num_Comensales)>
<!ELEMENT Fecha_hora (#PCDATA)>
<!ELEMENT Mesa (#PCDATA)>
<!ELEMENT Num_Comensales (#PCDATA)>
<!ELEMENT Tipos_Platos (Tipo+)>
<!ELEMENT Tipo (Codigo,Nombre,Descripcion)>
<!ELEMENT Pedidos_Platos (Pedido_Plato+)>
<!ELEMENT Pedido_Plato (Codigo_ped,Codigo_plat,Unidades)>
<!ELEMENT Codigo_ped (#PCDATA)>
<!ELEMENT Codigo_plat (#PCDATA)>
<!ELEMENT Unidades (#PCDATA)>
<!ELEMENT Alergenos_Platos (Alergeno_Plato+)>
<!ELEMENT Alergeno_Plato (#PCDATA|Codigo_alerg|Codigo_plat)*>
<!ELEMENT Codigo_alerg (#PCDATA)>
<!ELEMENT Pedidos_Promociones (Pedido_Promocion+)>
<!ELEMENT Pedido_Promocion (Codigo_ped,Codigo_prom)>
<!ELEMENT Codigo_prom (#PCDATA)>

=== crlizcan/CloudWeb/Lenguajes de marcas/ResOdi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ResOdi SYSTEM "ResOdi.dtd">
<ResOdi>
    <Administradores>
        <Cuenta>
            <Usuario>Alejandro_Robles@res.odisea.org</Usuario>
            <Password>ar03052023</Password>
            <NIF>58578286T</NIF>
            <Nombre>Alejandro</Nombre>
            <Apellidos>Robles Correa</Apellidos>
            <Telefono>692211271</Telefono>
            <Direccion>C// Calvo Sotelo 9 BajoD 28931 Mostoles Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>Carlos_Gutierrez@res.odisea.org</Usuario>
            <Password>cg03052023</Password>
            <NIF>97453211A</NIF>
            <Nombre>Carlos</Nombre>
            <Apellidos>Gutierrez Benjarano</Apellidos>
            <Telefono>717893004</Telefono>
            <Direccion>C// Pelayo 1 1ºC 28004 Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>Desire_Sanchez00@res.odisea.org</Usuario>
            <Password>ds03052023</Password>
            <NIF>82176339F</NIF>
            <Nombre>Desire</Nombre>
            <Apellidos>Sanchez Rojo</Apellidos>
            <Telefono>693475110</Telefono>
            <Direccion>C// Apodaca 12 3ºA 28004 Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>Jaime_Gonzalez00@res.odisea.org</Usuario>
            <Password>jg03052023</Password>
            <NIF>77496879N</NIF>
            <Nombre>Jaime</Nombre>
            <Apellidos>Gonzalez Martin</Apellidos>
            <Telefono>692202122</Telefono>
            <Direccion>C// Apodaca 12 3ºA 28004 Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>Monica_Gomez@res.odisea.org</Usuario>
            <Password>mg03052023</Password>
            <NIF>81006728S</NIF>
            <Nombre>Monica</Nombre>
            <Apellidos>Gomez Moreno</Apellidos>
            <Telefono>682718485</Telefono>
            <Direccion>C// Rafael Canogar 6 3ºB 28521 Rivas-Vaciamadrid Madrid</Direccion>
        </Cuenta>
    </Administradores>
    <Usuarios>
        <Cuenta>
            <Usuario>Carmengonz@gmail.es</Usuario>
            <Password>franymarcos00y05</Password>
            <Nombre>Carmen</Nombre>
            <Apellidos>Ruiz Castillo</Apellidos>
            <Telefono>729030302</Telefono>
            <Direccion>C// La huerta 5 28850 Torrejon de Ardoz Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>DeathSlayer@gmail.com</Usuario>
            <Password>123PedroPascalLOVE</Password>
            <Nombre>Maria Teresa</Nombre>
            <Apellidos>Gutierrez Hidalgo</Apellidos>
            <Telefono>648194032</Telefono>
            <Direccion>C// Laguna 23 1ºD 28047 Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>Elaine98@hotmail.com</Usuario>
            <Password>elenisQuinn773</Password>
            <Nombre>Elena</Nombre>
            <Apellidos>García Torres</Apellidos>
            <Telefono>692734011</Telefono>
            <Direccion>C// Oviedo 24 5ºF 28934 Mostoles Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>HelloKitty88@outlook.es</Usuario>
            <Password>11jenlo23</Password>
            <Nombre>Evelyn</Nombre>
            <Apellidos>Cortes Quesada</Apellidos>
            <Telefono>683942018</Telefono>
            <Direccion>C// Regil 32 BajoA 28041 Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>Jameslebron22@outlook.com</Usuario>
            <Password>93MJking95</Password>
            <Nombre>Ruben</Nombre>
            <Apellidos>Lopez Navarro</Apellidos>
            <Telefono>694027481</Telefono>
            <Direccion>C// Bilbao 15 28223 Pozuelo de Alarcon Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>LuisFDZ@hotmail.com</Usuario>
            <Password>aj23eq2e3oo3p68d</Password>
            <Nombre>Luis</Nombre>
            <Apellidos>Fernandez Pacheco</Apellidos>
            <Telefono>713749010</Telefono>
            <Direccion>C// Salsipuedes 9 2ºC 28021 Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>Musicoffskin12@outlook.es</Usuario>
            <Password>19kk94</Password>
            <Nombre>Roberto</Nombre>
            <Apellidos>Mata del Campo</Apellidos>
            <Telefono>691020394</Telefono>
            <Direccion>C// Barrafon 29 2ºA 28011 Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>NurseyBoy00@gmail.es</Usuario>
            <Password>ui1jrew131hg</Password>
            <Nombre>Marcos</Nombre>
            <Apellidos>FIsher del Rio</Apellidos>
            <Telefono>629310375</Telefono>
            <Direccion>C// Sierra 80 BajoC 28038 Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>Raul.pichichi@gmail.com</Usuario>
            <Password>14halaMadrid14</Password>
            <Nombre>Raul</Nombre>
            <Apellidos>Turnagiu</Apellidos>
            <Telefono>619030475</Telefono>
            <Direccion>C// Pozano 11 BajoD 28010 Madrid</Direccion>
        </Cuenta>
        <Cuenta>
            <Usuario>Twomad360@outlook.es</Usuario>
            <Password>OWmama2834</Password>
            <Nombre>Alex</Nombre>
            <Apellidos>Morgan</Apellidos>
            <Telefono>639102034</Telefono>
            <Direccion>C// Viloria de la Rioja 21 3ºB 28050 Madrid</Direccion>
        </Cuenta>
    </Usuarios>
    <Incidencias>
        <Incidencia>
            <Codigo>IC001</Codigo>
            <Descripcion>No se ha entregado todo lo figurado en el pedido.</Descripcion>
            <Fecha_Inicio>2023-05-05</Fecha_Inicio>
            <Fecha_Solucion>2023-05-05</Fecha_Solucion>
            <Usuario_Admin>Monica_Gomez@res.odisea.org</Usuario_Admin>
            <Usuario_Usu>NurseyBoy00@gmail.es</Usuario_Usu>
        </Incidencia>
        <Incidencia>
            <Codigo>IC002</Codigo>
            <Descripcion>El pedido llegó con retraso debido a la avería del vehículo del repartidor.</Descripcion>
            <Fecha_Inicio>2023-05-06</Fecha_Inicio>

            <Usuario_Admin>Carlos_Gutierrez@res.odisea.org</Usuario_Admin>
            <Usuario_Usu>LuisFDZ@hotmail.com</Usuario_Usu>
        </Incidencia>
        <Incidencia>
            <Codigo>IC003</Codigo>
            <Descripcion>A la hora de pagar en efectivo, la tarjeta no funcionaba correctamente.</Descripcion>
            <Fecha_Inicio>2023-05-06</Fecha_Inicio>
            <Fecha_Solucion>2023-05-06</Fecha_Solucion>
            <Usuario_Admin>Desire_Sanchez00@res.odisea.org</Usuario_Admin>
            <Usuario_Usu>HelloKitty88@outlook.es</Usuario_Usu>
        </Incidencia>
        <Incidencia>
            <Codigo>IC004</Codigo>
            <Descripcion>Retraso en la entrega del pedido por desorientación del repartidor.</Descripcion>
            <Fecha_Inicio>2023-05-06</Fecha_Inicio>
            <Fecha_Solucion>2023-05-06</Fecha_Solucion>
            <Usuario_Admin>Alejandro_Robles@res.odisea.org</Usuario_Admin>
            <Usuario_Usu>Jameslebron22@outlook.com</Usuario_Usu>
        </Incidencia>
        <Incidencia>
            <Codigo>IC005</Codigo>
            <Descripcion>El cliente introdujo la dirección erróneamente.</Descripcion>
            <Fecha_Inicio>2023-05-07</Fecha_Inicio>
            <Usuario_Admin>Carlos_Gutierrez@res.odisea.org</Usuario_Admin>
            <Usuario_Usu>HelloKitty88@outlook.es</Usuario_Usu>
        </Incidencia>
        <Incidencia>
            <Codigo>IC006</Codigo>
            <Descripcion>Problemas en la cocina con uno de los fuegos, se retrasó un pedido</Descripcion>
            <Fecha_Inicio>2023-05-07</Fecha_Inicio>
            <Fecha_Solucion>2023-05-08</Fecha_Solucion>
            <Usuario_Admin>Monica_Gomez@res.odisea.org</Usuario_Admin>
            <Usuario_Usu>Musicoffskin12@outlook.es</Usuario_Usu>
        </Incidencia>
        <Incidencia>
            <Codigo>IC007</Codigo>
            <Descripcion>Por indisponibilidad de un empleado, se ha cancelado un pedido</Descripcion>
            <Fecha_Inicio>2023-05-08</Fecha_Inicio>
            <Usuario_Admin>Desire_Sanchez00@res.odisea.org</Usuario_Admin>
            <Usuario_Usu>Twomad360@outlook.es</Usuario_Usu>
        </Incidencia>
        <Incidencia>
            <Codigo>IC008</Codigo>
            <Descripcion>Unido a la incidencia 9, se han intercambiado pedidos inintencionadamente.</Descripcion>
            <Fecha_Inicio>2023-05-09</Fecha_Inicio>
            <Usuario_Admin>Alejandro_Robles@res.odisea.org</Usuario_Admin>
            <Usuario_Usu>Carmengonz@gmail.es</Usuario_Usu>
        </Incidencia>
        <Incidencia>
            <Codigo>IC009</Codigo>
            <Descripcion>Unido a la incidencia 8, se han intercambiado pedidos inintencionadamente.</Descripcion>
            <Fecha_Inicio>2023-05-09</Fecha_Inicio>
            <Usuario_Admin>Alejandro_Robles@res.odisea.org</Usuario_Admin>
            <Usuario_Usu>Elaine98@hotmail.com</Usuario_Usu>
        </Incidencia>
    </Incidencias>
    <Platos>
        <Plato>
            <Codigo>BB-01AA</Codigo>
            <Nombre>Agua grande</Nombre>
            <Codigo_tipo>BBD</Codigo_tipo>
            <Precio>3</Precio>
        </Plato>
        <Plato>
            <Codigo>BB-02AA</Codigo>
            <Nombre>Coca-cola</Nombre>
            <Codigo_tipo>BBD</Codigo_tipo>
            <Precio>3.5</Precio>
        </Plato>
        <Plato>
            <Codigo>BB-03AA</Codigo>
            <Nombre>Nestea</Nombre>
            <Codigo_tipo>BBD</Codigo_tipo>
            <Precio>3.5</Precio>
        </Plato>
        <Plato>
            <Codigo>BB-04AA</Codigo>
            <Nombre>Fanta limon</Nombre>
            <Codigo_tipo>BBD</Codigo_tipo>
            <Precio>3.5</Precio>
        </Plato>
        <Plato>
            <Codigo>BB-05AA</Codigo>
            <Nombre>Fanta naranja</Nombre>
            <Codigo_tipo>BBD</Codigo_tipo>
            <Precio>3.5</Precio>
        </Plato>
        <Plato>
            <Codigo>BB-06AA</Codigo>
